language: node_js
node_js:
  - "10.5.0"
  - "9.11.2"
  - "8.12.0"
  - "7.10.1"
  - "7.0.0"
script:
  - npm run build
addons:
  apt:
    pacakges:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
notifications:
  slack: flounder:CxUpXbQ1rlErXZR5xEqvNy2b
