language: node_js
node_js:
  - "8.1.2"
  - "7.7.1"
  - "6.11.0"
  - "5.0.0"
script:
  - npm run build
addons:
  apt:
    pacakges:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
notifications:
  slack: flounder:CxUpXbQ1rlErXZR5xEqvNy2b
